# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site favicons & manifest icons
# 9. Site navigation

# run locally: bundle exec jekyll serve
# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec
- .jekyll-cache

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# 3. Gem settings
paginate: 2 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: fstona # jekyll-seo-tag > Owners twitter username
author: Filipe Stona # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Filipe Stona # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/fstona
    - https://www.linkedin.com/in/filipe-stona-6917181b
    - https://github.com/fstona
# markdown: CommonMark # Markdown parse settings, CommonMark performs slightly better an others in build time
# commonmark:
  # options: ["SMART", "FOOTNOTES"]
  # extensions: ["strikethrough", "autolink", "table"]

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/London # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    description: "Nessa seção vou me dedicar a escrever sobre assuntos diversos do meu interesse, principalmente relacionados a economia e computação." # The post list page content
    feature_text: |
    feature_image: "https://cms.qz.com/wp-content/uploads/2017/07/pen-on-journal.jpg?quality=75&strip=all&w=1600&h=900&crop=1"

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/default-social-image.png" # Default image for sharing
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-US # Set the site language
title: "Filipe Stona" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logos/ufrgsLogo2.jpg" # Site logo, also used in jekyll-seo-tag
description: "PhD in Economics at UFRGS and Economist at Bradesco Asset" # Site description and default description, also used in jekyll-seo-tag
subdescription: "My primary research interests are in the formulation and computation of dynamic equilibrium models."
url: "fstona.github.io" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "https://github.com/fstona"
email: "mailto:fstona@live.com"
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
# google_analytics: ''
# google_analytics_anonymize_ip: ''
# service_worker: false # Will turn off the service worker if set to false
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 8. Site favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: '/assets/logos/ufrgsLogo@16px.jpg'
  32: '/assets/logos/ufrgsLogo@32px.jpg'
  96: '/assets/logos/ufrgsLogo@96px.jpg'
  120: '/assets/logos/ufrgsLogo@96px.jpg'
  144: '/assets/logos/ufrgsLogo@96px.jpg'
  180: '/assets/logos/ufrgsLogo@96px.jpg'
  512: '/assets/logos/ufrgsLogo@96px.jpg'
  1024: '/assets/logos/ufrgsLogo@96px.jpg'

# 9. Site navigation
navigation_header:
- title: Home
  url: /
- title: Research
  url: /research/
#- title: Research
#  url: /elements/
#- title: Teaching
#  url: /categories/
#- title: Search
#  url: /search/
- title: External Resources
  url: /external/
- title: Blog
  url: /blog/
- title: More
  url: /more/

navigation_footer:
- title: Alembic Template
  url: https://darn.es

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com/fstona
  LinkedIn: https://www.linkedin.com/in/filipe-stona-6917181b
  GitHub: https://github.com/fstona
  email: mailto:fstona@live.com
  link: https://www.researchgate.net/profile/Filipe_Stona2
  RSS: /feed.xml

sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
  Twitter: "#0d94e7"
  facebook: false
  Email: true
  LinkedIn: true
